# Generated by Django 5.2 on 2025-04-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuk_tuk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
    ]
