# Generated by Django 5.2 on 2025-04-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuk_tuk', '0003_driverroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverroute',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='السرعة (كم/ساعة)'),
        ),
    ]
